### ISSUE TITLE
Change the DNS for the mink.behat.org domain

### ISSUE THREAD

**Issue by stof** [minkphp/docs#41]
It currently redirects to the Behat/Mink repo on Github. This will become wrong anyway when moving the code to the minkphp organization. We should update the domain to point to RTD

**Comment by stof** [comment]
Actually, the DNS is pointing to the documentation repo, which gets redirected properly by Github and so it points here.

@everzet can you update the DNS to be a CNAME to mink.readthedocs.org ?

Once it is done, I will update the RTD config to make it the canonical URL.

**Comment by everzet** [comment]
done. Propagating.

**Comment by stof** [comment]
How long is the cache TTL on the DNS ? It still has not propagated to me.

**Comment by aik099** [comment]
I've made DNS query directly to `behat.org` DNS provider and it's not showing any CNAME for `mink.behat.org`.

**Comment by everzet** [comment]
I set the redirect instead of CNAME. Sorry guys. Should be fixed in couple of hours now.

**Comment by stof** [comment]
Working for me (after I clear my Firefox network cache to make it forget the 301 redirect to the Github repo). So I'm closing this issue
