### ISSUE TITLE
HTTPS for the doc

### ISSUE THREAD

**Issue by stof** [minkphp/docs#84]
ReadtheDocs now supports HTTPS for custom domains, but this requires migrating the CNAME to the new target (old CNAMEs don't support it).

@everzet as you are the one controlling the DNS of the domain (at least as far as I know), could you update it to point at `readthedocs.io` ? https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl

**Comment by stof** [comment]
@ciaranmcnulty do you have access to the behat.org DNS ?

**Comment by everzet** [comment]
I own the Behat.org, but not Mink's ReadTheDocs account.

Done:
<img width="1010" alt="Screenshot 2021-10-06 at 15 49 48" src="https://user-images.githubusercontent.com/30813/136227731-696c641e-cce6-4635-acf0-10bb83c5e578.png">

**Comment by stof** [comment]
I'm the owner of the readthedocs account. And HTTPS now works on the website.

**Comment by everzet** [comment]
\o/
